[tox]
envlist = py310,py311,py312,lint
skip_missing_interpreters = true

[testenv]
description = Run unit tests with coverage
package = editable
extras = dev
commands =
    coverage run -m pytest
    coverage report -m

[testenv:lint]
description = Run static checks
package = skip
deps =
    ruff==0.6.9
commands =
    ruff check .
